name: Build for Platforms
on:
  push:
    branches:
      - dev
jobs:
  # setup-project:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: setup project dependencies
  #       run: |
  #         npm run dev-setup

  build-web:
    # needs: setup-project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup project dependencies
        run: |
          npm run dev-setup
      - name: Build for web
        run: |
          cd template && npm run web:build
      - name: Upload Android Artifact
        uses: actions/upload-artifact@v2
        with: 
          name: build
          path: template/dist/

  # build-android:
  #   needs: setup-project
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: setup project dependencies
  #       run: |
  #         npm run dev-setup
  #     - name: Build Android Release
  #       run: |
  #         cd template && cd android && ./gradlew assembleRelease

  # build-ios:
  #   # needs: setup-project
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: setup project dependencies
  #       run: |
  #         npm run dev-setup
  #     - name: Install pod dependencies
  #       run: |
  #         cd template && cd ios && pod install
  #     - name: Build IOS app
  #       run: |
  #         xcodebuild -workspace template/ios/HelloWorld.xcworkspace -scheme HelloWorld archive -archivePath template/ios/HelloWorld.xcarchive
  #         xcodebuild -exportArchive -archivePath template/ios/HelloWorld.xcarchive -exportPath . -exportOptionsPlist template/ios/HelloWorld/Info.plist
      

  # buid-macOS:
  #   # needs: setup-project
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: setup project dependencies
  #       run: |
  #         npm run dev-setup
  #     - name: Build macOS app
  #       run: |
  #         cd template && npm run mac:build
  #     - name: see directory
  #       run: |
  #         ls

  # buid-windows:
  #   # needs: setup-project
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: setup project dependencies
  #       run: |
  #         npm run dev-setup
  #     - name: Build windows app
  #       run: |
  #         cd template && npm run windows:build
  #     - name: see directory
  #       run: |
  #         ls